### ISSUE TITLE
Wrong response after consecutive runs of Closure

### ISSUE THREAD

**Issue by borelian** [hochbaumGroup/closure-problem#4]
I'm having strange behaviour when I re-run the Closure function over the same graph but with different weights.

For example, following your example. If I run 
```
G = nx.DiGraph()
G.add_node(0, weight=0)
G.add_node(1, weight=0)
G.add_node(2, weight=0)
G.add_edge(0, 1, weight=1)
G.add_edge(0, 2, weight=1)
G.add_edge(1, 2, weight=1)
nx.set_node_attributes(G,{0: 3, 1: -6, 2: 4},'weight')
Closure(G).solve()
```
I get `{1, 2}` as expected.

If I reset the weight values and re-run `Closure()` function, I get unexpected results:

```
nx.set_node_attributes(G,{0: -1, 1: -1, 2: -1},'weight')
Closure(G).solve()
````
I get empty set.   If I come back to the original values:
```
nx.set_node_attributes(G,{0: 3, 1: -6, 2: 4},'weight')
Closure(G).solve()
```
I get `{0,1,2}`

**Comment by borelian** [comment]
Apparently, the problem is with the new created `'sink'` and `'source'` node, with a given weight.    If I remove this node  from the graph and re-run, it works.

**Comment by quic0** [comment]
Thanks for flagging it. I'll take a look.

**Comment by quic0** [comment]
This is likely caused by closure modifying the graph instead of copying it.

**Comment by quic0** [comment]
The graph is now copied, so the original graph doesn't change and the second run returns the same result.
